name: ci

on:
  push:
    branches:
      - master
      - github-actions
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ SECRETS.GH_TOKEN }}
      GIT_AUTHOR_NAME: LiteX Robot
      GIT_AUTHOR_EMAIL: robot@timvideos.us
      GH_USER: symbiflow-robot
      GIT_MODE : https
    steps:
      - uses: actions/checkout@v4

      # Checkout Repository
      - name: Checkout
        run: git fetch --prune --unshallow --tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Install Tools
      - name: Install Tools
        run: |
          sudo apt-get install wget build-essential python3
          pip3 install setuptools wheel
          pip3 install -r requirements.txt

      # Update
      - name: Update
        run: |
          sudo git config --system --replace-all user.email "$GIT_AUTHOR_EMAIL"
          sudo git config --system --replace-all user.name "$GIT_AUTHOR_NAME"
          if [ "${{ github.repository_owner }}" = "litex-hub" ]; then
            ./update.py --push
          else
            ./update.py
          fi

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
